export BAT_THEME=Coldark-Dark
export EDITOR=/usr/bin/vim
export GOROOT=/usr/local/go
export HISTCONTROL=ignoreboth
export VSCODEPATH="/Applications/Visual Studio Code.app/Contents/Resources/app"

[[ -x /opt/homebrew/bin/brew ]] && eval "$(/opt/homebrew/bin/brew shellenv)"
[[ -d "${GOROOT}" ]] && export PATH="${GOROOT}/bin:${PATH}"
[[ -d "${VSCODEPATH}" ]] && export PATH="${VSCODEPATH}/bin:${PATH}"

[[ -s "${HOME}/.bashrc" ]] && \. "${HOME}/.bashrc"
